// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: id.proto

#ifndef PROTOBUF_INCLUDED_id_2eproto
#define PROTOBUF_INCLUDED_id_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_id_2eproto 

namespace protobuf_id_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_id_2eproto
namespace IDIncrement {
class IDRequest;
class IDRequestDefaultTypeInternal;
extern IDRequestDefaultTypeInternal _IDRequest_default_instance_;
class IDResponse;
class IDResponseDefaultTypeInternal;
extern IDResponseDefaultTypeInternal _IDResponse_default_instance_;
}  // namespace IDIncrement
namespace google {
namespace protobuf {
template<> ::IDIncrement::IDRequest* Arena::CreateMaybeMessage<::IDIncrement::IDRequest>(Arena*);
template<> ::IDIncrement::IDResponse* Arena::CreateMaybeMessage<::IDIncrement::IDResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace IDIncrement {

// ===================================================================

class IDRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:IDIncrement.IDRequest) */ {
 public:
  IDRequest();
  virtual ~IDRequest();

  IDRequest(const IDRequest& from);

  inline IDRequest& operator=(const IDRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  IDRequest(IDRequest&& from) noexcept
    : IDRequest() {
    *this = ::std::move(from);
  }

  inline IDRequest& operator=(IDRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IDRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IDRequest* internal_default_instance() {
    return reinterpret_cast<const IDRequest*>(
               &_IDRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(IDRequest* other);
  friend void swap(IDRequest& a, IDRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline IDRequest* New() const final {
    return CreateMaybeMessage<IDRequest>(NULL);
  }

  IDRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<IDRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const IDRequest& from);
  void MergeFrom(const IDRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IDRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string page_table_no = 1;
  bool has_page_table_no() const;
  void clear_page_table_no();
  static const int kPageTableNoFieldNumber = 1;
  const ::std::string& page_table_no() const;
  void set_page_table_no(const ::std::string& value);
  #if LANG_CXX11
  void set_page_table_no(::std::string&& value);
  #endif
  void set_page_table_no(const char* value);
  void set_page_table_no(const char* value, size_t size);
  ::std::string* mutable_page_table_no();
  ::std::string* release_page_table_no();
  void set_allocated_page_table_no(::std::string* page_table_no);

  // @@protoc_insertion_point(class_scope:IDIncrement.IDRequest)
 private:
  void set_has_page_table_no();
  void clear_has_page_table_no();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr page_table_no_;
  friend struct ::protobuf_id_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class IDResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:IDIncrement.IDResponse) */ {
 public:
  IDResponse();
  virtual ~IDResponse();

  IDResponse(const IDResponse& from);

  inline IDResponse& operator=(const IDResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  IDResponse(IDResponse&& from) noexcept
    : IDResponse() {
    *this = ::std::move(from);
  }

  inline IDResponse& operator=(IDResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IDResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IDResponse* internal_default_instance() {
    return reinterpret_cast<const IDResponse*>(
               &_IDResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(IDResponse* other);
  friend void swap(IDResponse& a, IDResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline IDResponse* New() const final {
    return CreateMaybeMessage<IDResponse>(NULL);
  }

  IDResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<IDResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const IDResponse& from);
  void MergeFrom(const IDResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IDResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 s_id = 2;
  bool has_s_id() const;
  void clear_s_id();
  static const int kSIdFieldNumber = 2;
  ::google::protobuf::int64 s_id() const;
  void set_s_id(::google::protobuf::int64 value);

  // required int64 m_id = 3;
  bool has_m_id() const;
  void clear_m_id();
  static const int kMIdFieldNumber = 3;
  ::google::protobuf::int64 m_id() const;
  void set_m_id(::google::protobuf::int64 value);

  // required int32 part_id = 1;
  bool has_part_id() const;
  void clear_part_id();
  static const int kPartIdFieldNumber = 1;
  ::google::protobuf::int32 part_id() const;
  void set_part_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:IDIncrement.IDResponse)
 private:
  void set_has_part_id();
  void clear_has_part_id();
  void set_has_s_id();
  void clear_has_s_id();
  void set_has_m_id();
  void clear_has_m_id();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int64 s_id_;
  ::google::protobuf::int64 m_id_;
  ::google::protobuf::int32 part_id_;
  friend struct ::protobuf_id_2eproto::TableStruct;
};
// ===================================================================

class IDService_Stub;

class IDService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline IDService() {};
 public:
  virtual ~IDService();

  typedef IDService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void IDInc(::google::protobuf::RpcController* controller,
                       const ::IDIncrement::IDRequest* request,
                       ::IDIncrement::IDResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(IDService);
};

class IDService_Stub : public IDService {
 public:
  IDService_Stub(::google::protobuf::RpcChannel* channel);
  IDService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~IDService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements IDService ------------------------------------------

  void IDInc(::google::protobuf::RpcController* controller,
                       const ::IDIncrement::IDRequest* request,
                       ::IDIncrement::IDResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(IDService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IDRequest

// required string page_table_no = 1;
inline bool IDRequest::has_page_table_no() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void IDRequest::set_has_page_table_no() {
  _has_bits_[0] |= 0x00000001u;
}
inline void IDRequest::clear_has_page_table_no() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void IDRequest::clear_page_table_no() {
  page_table_no_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_page_table_no();
}
inline const ::std::string& IDRequest::page_table_no() const {
  // @@protoc_insertion_point(field_get:IDIncrement.IDRequest.page_table_no)
  return page_table_no_.GetNoArena();
}
inline void IDRequest::set_page_table_no(const ::std::string& value) {
  set_has_page_table_no();
  page_table_no_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:IDIncrement.IDRequest.page_table_no)
}
#if LANG_CXX11
inline void IDRequest::set_page_table_no(::std::string&& value) {
  set_has_page_table_no();
  page_table_no_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:IDIncrement.IDRequest.page_table_no)
}
#endif
inline void IDRequest::set_page_table_no(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_page_table_no();
  page_table_no_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:IDIncrement.IDRequest.page_table_no)
}
inline void IDRequest::set_page_table_no(const char* value, size_t size) {
  set_has_page_table_no();
  page_table_no_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:IDIncrement.IDRequest.page_table_no)
}
inline ::std::string* IDRequest::mutable_page_table_no() {
  set_has_page_table_no();
  // @@protoc_insertion_point(field_mutable:IDIncrement.IDRequest.page_table_no)
  return page_table_no_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* IDRequest::release_page_table_no() {
  // @@protoc_insertion_point(field_release:IDIncrement.IDRequest.page_table_no)
  if (!has_page_table_no()) {
    return NULL;
  }
  clear_has_page_table_no();
  return page_table_no_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void IDRequest::set_allocated_page_table_no(::std::string* page_table_no) {
  if (page_table_no != NULL) {
    set_has_page_table_no();
  } else {
    clear_has_page_table_no();
  }
  page_table_no_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), page_table_no);
  // @@protoc_insertion_point(field_set_allocated:IDIncrement.IDRequest.page_table_no)
}

// -------------------------------------------------------------------

// IDResponse

// required int32 part_id = 1;
inline bool IDResponse::has_part_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void IDResponse::set_has_part_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void IDResponse::clear_has_part_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void IDResponse::clear_part_id() {
  part_id_ = 0;
  clear_has_part_id();
}
inline ::google::protobuf::int32 IDResponse::part_id() const {
  // @@protoc_insertion_point(field_get:IDIncrement.IDResponse.part_id)
  return part_id_;
}
inline void IDResponse::set_part_id(::google::protobuf::int32 value) {
  set_has_part_id();
  part_id_ = value;
  // @@protoc_insertion_point(field_set:IDIncrement.IDResponse.part_id)
}

// required int64 s_id = 2;
inline bool IDResponse::has_s_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void IDResponse::set_has_s_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void IDResponse::clear_has_s_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void IDResponse::clear_s_id() {
  s_id_ = GOOGLE_LONGLONG(0);
  clear_has_s_id();
}
inline ::google::protobuf::int64 IDResponse::s_id() const {
  // @@protoc_insertion_point(field_get:IDIncrement.IDResponse.s_id)
  return s_id_;
}
inline void IDResponse::set_s_id(::google::protobuf::int64 value) {
  set_has_s_id();
  s_id_ = value;
  // @@protoc_insertion_point(field_set:IDIncrement.IDResponse.s_id)
}

// required int64 m_id = 3;
inline bool IDResponse::has_m_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void IDResponse::set_has_m_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void IDResponse::clear_has_m_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void IDResponse::clear_m_id() {
  m_id_ = GOOGLE_LONGLONG(0);
  clear_has_m_id();
}
inline ::google::protobuf::int64 IDResponse::m_id() const {
  // @@protoc_insertion_point(field_get:IDIncrement.IDResponse.m_id)
  return m_id_;
}
inline void IDResponse::set_m_id(::google::protobuf::int64 value) {
  set_has_m_id();
  m_id_ = value;
  // @@protoc_insertion_point(field_set:IDIncrement.IDResponse.m_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace IDIncrement

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_id_2eproto
